config:
  enable_tls: true
  create_cert_manager_issuer: true

secrets:
  langfuse:
    INIT_USER_PASSWORD:
    INIT_PROJECT_SECRET_KEY:
    INIT_PROJECT_PUBLIC_KEY:
  api:
    OPENAI_API_KEY:
    ANTHROPIC_API_KEY:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    GEE_SERVICE_ACCOUNT_JSON:
    MAPBOX_API_TOKEN:
    GFW_DATA_API_KEY:
    GFW_DATA_API_USER_ID:
    ELEVENLABS_API_KEY:

langfuse:
  enabled: true
  host: langfuse.zeno.ds.io

api:
  host: api.zeno.ds.io
  replicas: 1
  image:
    repository: public.ecr.aws/b7u8b0a6/project-zeno/zeno
    tag: 2757f359105a9738086f1d07ac2e8200cca9675d
  config:
    LANGFUSE_HOST: https://langfuse.zeno.ds.io
    OLLAMA_BASE_URL: http://ollama.default.svc.cluster.local:11434

streamlit:
  host: streamlit.zeno.ds.io
  config:
    API_BASE_URL: https://api.zeno.ds.io
