config:
  enable_tls: true
  # we will use the existing cluster issuer from default namespace
  create_cert_manager_issuer: false

secrets:
  langfuse:
    INIT_USER_PASSWORD:
    INIT_PROJECT_SECRET_KEY:
    INIT_PROJECT_PUBLIC_KEY:
  api:
    OPENAI_API_KEY:
    ANTHROPIC_API_KEY:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:

langfuse:
  enabled: false

api:
  host: dev.api.zeno.ds.io
  replicas: 1
  image:
    repository: public.ecr.aws/b7u8b0a6/project-zeno/zeno
    tag: 0b9285335d8231f4a4747efa29aedc45c7f6c38f
  config:
    LANGFUSE_HOST: https://langfuse.zeno.ds.io
