# Global configuration
global:
  environment: default

# Dependency configurations
ollama:
  enabled: true
  models:
    # - llama3.2
    - nomic-embed-text

langfuse:
  enabled: true
  
  # Database configuration
  database:
    type: postgres
    url: ${DATABASE_URL}
    encryptionKey: ${ENCRYPTION_KEY}

  # Redis configuration (in-cluster)
  redis:
    enabled: true
    architecture: standalone
    persistence:
      enabled: true
      storageClass: "gp2"
      size: 1Gi

  # ClickHouse configuration (in-cluster)
  clickhouse:
    enabled: true
    persistence:
      enabled: true
      storageClass: "gp2"
      size: 10Gi

  # Authentication
  auth:
    disableSignup: true
    nextauth:
      secret: ${NEXTAUTH_SECRET}
      url: "https://langfuse.zeno.ds.io"

  # Ingress configuration
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "langfuse.zeno.ds.io"
        paths:
          - path: /
            pathType: Prefix

# Zeno application configuration
zeno:
  config:
    enable_tls: true
    create_cert_manager_issuer: true

  secrets:
    langfuse:
      NEXTAUTH_SECRET:      # Required for v3
      ENCRYPTION_KEY:       # Required for v3
      PROJECT_PUBLIC_KEY:   # Changed from INIT_PROJECT_PUBLIC_KEY
      PROJECT_SECRET_KEY:   # Changed from INIT_PROJECT_SECRET_KEY
      POSTGRES_PASSWORD:
    api:
      OPENAI_API_KEY:
      ANTHROPIC_API_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      GEE_SERVICE_ACCOUNT_JSON:
      MAPBOX_API_TOKEN:
      GFW_DATA_API_KEY:
      GFW_DATA_API_USER_ID:
      ELEVENLABS_API_KEY:

  langfuse:
    enabled: true
    host: langfuse.zeno.ds.io

  api:
    host: api.zeno.ds.io
    replicas: 1
    resources:
      requests:
        cpu: "1000m"
        memory: "2Gi"
      limits:
        memory: "4Gi"
    image:
      repository: public.ecr.aws/b7u8b0a6/project-zeno/zeno
      tag: cb392bd2f999240b7ef8dd97634d290a292b7cd6
    config:
      LANGFUSE_HOST: https://langfuse.zeno.ds.io
      OLLAMA_BASE_URL: http://ollama.default.svc.cluster.local:11434
      DOMAINS_ALLOWLIST: "developmentseed.org,wri.org,wriconsultant.org"

  streamlit:
    host: streamlit.zeno.ds.io
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    config:
      API_BASE_URL: https://api.zeno.ds.io

  db:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD:
    POSTGRES_HOST:
    POSTGRES_DB: zeno_db
    image:
      repository: public.ecr.aws/b7u8b0a6/project-zeno/zeno-db
      tag: 36399544a758d4860dc23594d81e22b2c342172c
