zeno:
  langfuse:
    host: langfuse.zeno.ds.io
    postgresql:
      host: zeno-db.cv2oy6g4svaz.us-east-1.rds.amazonaws.com

  api:
    host: api.zeno.ds.io
    resources:
      requests:
        cpu: "1000m"    # 2 CPU cores
        memory: "2Gi"   # 4GB RAM
      limits:
        cpu: "1900m"    # 3 CPU cores max
        memory: "4Gi"   # 6GB RAM max
    config:
      LANGFUSE_HOST: https://langfuse.zeno.ds.io
      OLLAMA_BASE_URL: http://ollama.default.svc.cluster.local:11434

  streamlit:
    host: streamlit.zeno.ds.io
    resources:
      requests:
        cpu: "1000m"    # 1 CPU core
        memory: "1Gi"   # 2GB RAM
      limits:
        cpu: "1800m"    # 2 CPU cores max
        memory: "3Gi"   # 4GB RAM max
    config:
      API_BASE_URL: https://api.zeno.ds.io
      STREAMLIT_URL: https://streamlit.zeno.ds.io

  db:
    POSTGRES_HOST: zeno-db.cv2oy6g4svaz.us-east-1.rds.amazonaws.com

kube-prometheus-stack:
  grafana:
    ingress:
      hosts:
        - grafana.zeno.ds.io
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.zeno.ds.io
