# Global configuration
global:
  environment: default

# Dependency configurations
langfuse:
  fullnameOverride: "zeno" 
  langfuse:
    nextauth:
      url: http://localhost:3000
      secret:
        value: ""
    salt:
      value: ""
    features:
      telemetryEnabled: true
    ingress:
      enabled: true
      # This requires an ingress controller to be installed in the cluster
      # For example, using the nginx ingress controller:
      # helm install nginx-ingress ingress-nginx/ingress-nginx
      className: nginx
      tls:
        enabled: true
        secretName: langfuse-tls
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
    additionalEnv:
      - name: AUTH_DISABLE_SIGNUP
        value: "true"
      - name: LANGFUSE_INIT_ORG_ID
        value: "devseed"
      - name: LANGFUSE_INIT_PROJECT_ID
        value: "wri_lcl"
      - name: LANGFUSE_INIT_PROJECT_NAME
        value: "WRI Land Carbon Labs"
      - name: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
        valueFrom:
          secretKeyRef:
            name: zeno-langfuse-secrets
            key: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
      - name: LANGFUSE_INIT_PROJECT_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: zeno-langfuse-secrets
            key: LANGFUSE_INIT_PROJECT_SECRET_KEY
      - name: LANGFUSE_INIT_USER_EMAIL
        value: "info@developmentseed.org"
      - name: LANGFUSE_INIT_USER_NAME
        value: "devseed"
      - name: LANGFUSE_INIT_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zeno-langfuse-secrets
            key: LANGFUSE_INIT_USER_PASSWORD
  postgresql:
    deploy: false
    auth:
      username: postgres
      password:
      database: langfuse
  clickhouse:
    persistence:
      storageClass: "gp2"
    zookeeper:
      persistence:
        storageClass: "gp2"
    auth:
      existingSecret: zeno-langfuse-secrets
      existingSecretKey: CLICKHOUSE_PASSWORD
    resources:
      requests:
        memory: "1.5Gi"
        cpu: "500m"
      limits:
        memory: "3.5Gi"
        cpu: "750m"
  redis:
    primary:
      persistence:
        storageClass: "gp2"
    auth:
      existingSecret: zeno-langfuse-secrets
      existingSecretPasswordKey: REDIS_PASSWORD
  s3:
    deploy: false
    bucket: "langfuse-bucket"
    region: "us-east-1"
    endpoint: "https://s3.us-east-1.amazonaws.com"
    forcePathStyle: false
    accessKeyId:
      secretKeyRef:
        name: "langfuse-s3-credentials"
        key: "access_key_id"
    secretAccessKey:
      secretKeyRef:
        name: "langfuse-s3-credentials"
        key: "secret_access_key"
    eventUpload:
      prefix: "events/"
    batchExport:
      prefix: "exports/"
    mediaUpload:
      prefix: "media/"


# Zeno application configuration
zeno:
  config:
    enable_tls: true
    create_cert_manager_issuer: true

  # Environment variables - Secrets (add any new secrets here)
  env_secrets:
    OPENAI_API_KEY: ""
    ANTHROPIC_API_KEY: ""
    NEXTJS_API_KEY: ""
    MAPBOX_API_TOKEN: ""
    GFW_DATA_API_KEY: ""
    GFW_DATA_API_USER_ID: ""
    ELEVENLABS_API_KEY: ""
    GOOGLE_API_KEY: ""
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    COOKIE_SIGNER_SECRET_KEY: ""
    GEE_SERVICE_ACCOUNT_JSON: ""

  # Langfuse-specific secrets
  langfuse_secrets:
    LANGFUSE_INIT_USER_PASSWORD: ""
    LANGFUSE_INIT_PROJECT_SECRET_KEY: ""
    LANGFUSE_INIT_PROJECT_PUBLIC_KEY: ""
    CLICKHOUSE_PASSWORD: ""
    REDIS_PASSWORD: ""

  # Database secrets  
  db_secrets:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST: ""
    POSTGRES_DB: ""

  # Environment variables - Config (add any new config here)
  env_config:
    # Logging
    LOG_FORMAT: json
    LOG_LEVEL: info
    LOG_TO_FILE: "false"
    
    # External services
    LANGFUSE_HOST: https://langfuse.zeno.ds.io
    
    # API settings
    DOMAINS_ALLOWLIST: "developmentseed.org,wri.org,wriconsultant.org"
    AWS_DEFAULT_REGION: us-east-1
    GEE_SERVICE_ACCOUNT_PATH: /keys/zeno-gee-service-account.json
    MODEL: "gemini"
    

  langfuse:
    enabled: true
    host: langfuse.zeno.ds.io

  api:
    host: api.zeno.ds.io
    replicas: 2
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    resources:
      requests:
        cpu: "1000m"
        memory: "2Gi"
      limits:
        memory: "4Gi"
    image:
      repository: public.ecr.aws/b7u8b0a6/project-zeno/zeno
      tag: 0c7d973b5fff2654760f1e2f1d41043bf77ddbbd

  streamlit:
    host: streamlit.zeno.ds.io
    resources:
      requests:
        cpu: "100m"
        memory: "0.2Gi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    env_config:
      API_BASE_URL: https://api.zeno.ds.io
      LOCAL_API_BASE_URL: https://api.zeno.ds.io
      STREAMLIT_URL: https://streamlit.zeno.ds.io

  shell:
    replicas: 0
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"

  db:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD:
    POSTGRES_HOST:
    POSTGRES_DB: zeno_db
    image:
      repository: public.ecr.aws/b7u8b0a6/project-zeno/zeno-db
      tag: 77779ef2068328f1f8667a90b41c5aeb1ea1c658
