langfuse:
  langfuse:
    ingress:
      hosts:
      - host: langfuse.zeno.ds.io
        paths:
        - path: /
          pathType: Prefix
  postgresql:
    host: zeno-db.cv2oy6g4svaz.us-east-1.rds.amazonaws.com
  s3:
    bucket: "langfuse-production-bucket"

zeno:
  langfuse:
    host: langfuse.zeno.ds.io

  api:
    host: api.zeno.ds.io
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 15
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    resources:
      requests:
        cpu: "1000m"
        memory: "2Gi"
      limits:
        memory: "4Gi"
  env_config:
    LANGFUSE_HOST: https://langfuse.zeno.ds.io
    MODEL: "sonnet"

  streamlit:
    host: streamlit.zeno.ds.io
    env_config:
      API_BASE_URL: https://api.zeno.ds.io
      LOCAL_API_BASE_URL: https://api.zeno.ds.io
      STREAMLIT_URL: https://streamlit.zeno.ds.io

  db_secrets:
    POSTGRES_HOST: zeno-db.cv2oy6g4svaz.us-east-1.rds.amazonaws.com

kube-prometheus-stack:
  grafana:
    ingress:
      hosts:
        - grafana.zeno.ds.io
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.zeno.ds.io
