# Global configuration
global:
  environment: default

# Dependency configurations
ollama:
  enabled: true
  models:
    # - llama3.2
    - nomic-embed-text

langfuse:
  fullnameOverride: "zeno" 
  langfuse:
    nextauth:
      url: http://localhost:3000
      secret:
        value: ""
    salt:
      value: ""
    features:
      telemetryEnabled: true
    ingress:
      enabled: true
      # This requires an ingress controller to be installed in the cluster
      # For example, using the nginx ingress controller:
      # helm install nginx-ingress ingress-nginx/ingress-nginx
      className: nginx
      tls:
        enabled: true
        secretName: langfuse-tls
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
    additionalEnv:
      - name: AUTH_DISABLE_SIGNUP
        value: "true"
      - name: LANGFUSE_INIT_ORG_ID
        value: "devseed"
      - name: LANGFUSE_INIT_PROJECT_ID
        value: "wri_lcl"
      - name: LANGFUSE_INIT_PROJECT_NAME
        value: "WRI Land Carbon Labs"
      - name: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
        valueFrom:
          secretKeyRef:
            name: zeno-langfuse-secrets
            key: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
      - name: LANGFUSE_INIT_PROJECT_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: zeno-langfuse-secrets
            key: LANGFUSE_INIT_PROJECT_SECRET_KEY
      - name: LANGFUSE_INIT_USER_EMAIL
        value: "info@developmentseed.org"
      - name: LANGFUSE_INIT_USER_NAME
        value: "devseed"
      - name: LANGFUSE_INIT_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zeno-langfuse-secrets
            key: LANGFUSE_INIT_USER_PASSWORD
  postgresql:
    deploy: false
    auth:
      username: postgres
      password:
      database: langfuse
  clickhouse:
    persistence:
      storageClass: "gp2"
    zookeeper:
      persistence:
        storageClass: "gp2"
    auth:
      existingSecret: zeno-langfuse-secrets
      existingSecretKey: CLICKHOUSE_PASSWORD
  redis:
    primary:
      persistence:
        storageClass: "gp2"
    auth:
      existingSecret: zeno-langfuse-secrets
      existingSecretPasswordKey: REDIS_PASSWORD
  s3:
    deploy: false
    bucket: "langfuse-bucket"
    region: "us-east-1"
    endpoint: "https://s3.us-east-1.amazonaws.com"
    forcePathStyle: false
    accessKeyId:
      secretKeyRef:
        name: "langfuse-s3-credentials"
        key: "access_key_id"
    secretAccessKey:
      secretKeyRef:
        name: "langfuse-s3-credentials"
        key: "secret_access_key"
    eventUpload:
      prefix: "events/"
    batchExport:
      prefix: "exports/"
    mediaUpload:
      prefix: "media/"


# Zeno application configuration
zeno:
  config:
    enable_tls: true
    create_cert_manager_issuer: true

  secrets:
    langfuse:
      INIT_USER_PASSWORD:
      INIT_PROJECT_SECRET_KEY:
      INIT_PROJECT_PUBLIC_KEY:
    api:
      OPENAI_API_KEY:
      ANTHROPIC_API_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      GEE_SERVICE_ACCOUNT_JSON:
      MAPBOX_API_TOKEN:
      GFW_DATA_API_KEY:
      GFW_DATA_API_USER_ID:
      ELEVENLABS_API_KEY:

  langfuse:
    enabled: true
    host: langfuse.zeno.ds.io

  api:
    host: api.zeno.ds.io
    replicas: 3
    resources:
      requests:
        cpu: "1000m"
        memory: "2Gi"
      limits:
        memory: "4Gi"
    image:
      repository: public.ecr.aws/b7u8b0a6/project-zeno/zeno
      tag: e2bce83c51c4cf8d8b272fb5a678f0b9cb7f7805
    config:
      LANGFUSE_HOST: https://langfuse.zeno.ds.io
      OLLAMA_BASE_URL: http://ollama.default.svc.cluster.local:11434
      DOMAINS_ALLOWLIST: "developmentseed.org,wri.org,wriconsultant.org"

  streamlit:
    host: streamlit.zeno.ds.io
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    config:
      API_BASE_URL: https://api.zeno.ds.io

  db:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD:
    POSTGRES_HOST:
    POSTGRES_DB: zeno_db
    image:
      repository: public.ecr.aws/b7u8b0a6/project-zeno/zeno-db
      tag: 36399544a758d4860dc23594d81e22b2c342172c
