langfuse:
  nextauth:
    url: http://localhost:3000
    secret:
  salt:
  telemetryEnabled: true
  additionalEnv:
    - name: AUTH_DISABLE_SIGNUP
      value: "true"
    - name: LANGFUSE_INIT_ORG_ID
      value: "devseed"
    - name: LANGFUSE_INIT_PROJECT_ID
      value: "wri_lcl"
    - name: LANGFUSE_INIT_PROJECT_NAME
      value: "WRI Land Carbon Labs"
    - name: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          name: zeno-langfuse-secrets
          key: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
    - name: LANGFUSE_INIT_PROJECT_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: zeno-langfuse-secrets
          key: LANGFUSE_INIT_PROJECT_SECRET_KEY
    - name: LANGFUSE_INIT_USER_EMAIL
      value: "info@developmentseed.org"
    - name: LANGFUSE_INIT_USER_NAME
      value: "devseed"
    - name: LANGFUSE_INIT_USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: zeno-langfuse-secrets
          key: LANGFUSE_INIT_USER_PASSWORD

service:
  type: ClusterIP
  additionalLabels: []
ingress:
  enabled: false
  annotations: []
postgresql:
  deploy: false
  auth:
    username: postgres
    password:
    database: langfuse
  host:
