postgresql:
  type: "external-plaintext"
  external:
    port: "5432"
    database: "eoapi"
    credentials:
      username: "eoapi"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: eoapi.zeno-staging.ds.io
      paths:
        - path: /
          pathType: Prefix

namespace: eoapi
