postgresql:
  type: "external-plaintext"
  external:
    host: "${EOAPI_DB_HOST}"  # Will be replaced with terraform output
    port: "5432"
    database: "eoapi"
    credentials:
      username: "eoapi"
      password: "${EOAPI_DB_PASSWORD}"  # Will be set via GitHub secret

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: eoapi.zeno.ds.io
      paths:
        - path: /
          pathType: Prefix

namespace: eoapi
