# Default configuration for eoapi
raster:
  settings:
    envVars:
      AWS_REQUEST_PAYER: "requester"
    extraEnvFrom:
      - secretRef:
          name: requester-pays-s3-credentials
  command:
    - "uvicorn"
    - "titiler.pgstac.main:app"
    - "--host=$(HOST)"
    - "--port=$(PORT)"
    - "--log-level=debug"

postgresql:
  type: "external-secret"
  external:
    existingSecret:
      name: "eoapi-db-credentials"

postgrescluster:
  enabled: false

ingress:
  enabled: true
  pathSuffix: "(/|$)(.*)"
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  tls:
    enabled: true
    secretName: eoapi-tls
    certManager: false

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

namespace: eoapi
