grafana:
  enabled: false

prometheus:
  enabled: false
  alertmanager:
    enabled: false
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false

loki:
  image:
    tag: 2.9.10 # 3.x doesn't work well with loki-stack helm chart
