apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-zeno-config
data:
{{- range $key, $value := .Values.zeno.env_config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  API_BASE_URL: {{ printf "https://%s" .Values.zeno.api.host | quote }}