apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: zeno
    component: api
spec:
  replicas: {{ .Values.zeno.api.replicas | default 1 }}
  selector:
    matchLabels:
      app: zeno
      component: api
  template:
    metadata:
      labels:
        app: zeno
        component: api
      annotations:
        force-update: {{ randAlphaNum 5 | quote }}  # random annotation to force update
    spec:
      initContainers:
        - name: s3-data-sync
          image: amazon/aws-cli
          command: ['aws', 's3', 'sync', 's3://zeno-static-data', '/app/data']
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.zeno.api.config.AWS_REGION | default "us-east-1" }}"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      containers:
        - name: zeno-api
          image: "{{ .Values.zeno.api.image.repository }}:{{ .Values.zeno.api.image.tag }}"
          imagePullPolicy: "IfNotPresent"
          command: ["uv", "run", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
          resources:
            {{- toYaml .Values.zeno.api.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: OPENAI_API_KEY
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: ANTHROPIC_API_KEY
            - name: MAPBOX_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: MAPBOX_API_TOKEN
            - name: GFW_DATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: GFW_DATA_API_KEY
            - name: GFW_DATA_API_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: GFW_DATA_API_USER_ID
            - name: ELEVENLABS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: ELEVENLABS_API_KEY
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-langfuse-secrets
                  key: LANGFUSE_INIT_PROJECT_SECRET_KEY
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-langfuse-secrets
                  key: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
            - name: LANGFUSE_HOST
              value: {{ .Values.zeno.api.config.LANGFUSE_HOST }}
            - name: GEE_SERVICE_ACCOUNT_PATH
              value: /keys/zeno-gee-service-account.json
            - name: OLLAMA_BASE_URL
              value: {{ .Values.zeno.api.config.OLLAMA_BASE_URL }}
            - name: DOMAINS_ALLOWLIST
              value: {{ .Values.zeno.api.config.DOMAINS_ALLOWLIST | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: DATABASE_URL
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: gee-service-account
              mountPath: /keys
              readOnly: true
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: gee-service-account
          secret:
            secretName: {{ .Release.Name }}-zeno-secrets
            items:
              - key: GEE_SERVICE_ACCOUNT_JSON
                path: zeno-gee-service-account.json

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-streamlit
  labels:
    app: zeno
    component: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeno
      component: streamlit
  template:
    metadata:
      labels:
        app: zeno
        component: streamlit
      annotations:
        force-update: {{ randAlphaNum 5 | quote }}  # random annotation to force update
    spec:
      containers:
        - name: zeno-streamlit
          image: "{{ .Values.zeno.api.image.repository }}:{{ .Values.zeno.api.image.tag }}"
          imagePullPolicy: "IfNotPresent"
          command: ["uv", "run", "streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
          resources:
            {{- toYaml .Values.zeno.streamlit.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8501
              protocol: TCP
          env:
            - name: API_BASE_URL
              value: {{ .Values.zeno.streamlit.config.API_BASE_URL }}
            - name: LOCAL_API_BASE_URL
              value: {{ .Values.zeno.streamlit.config.API_BASE_URL }}
            - name: STREAMLIT_URL
              value: {{ .Values.zeno.streamlit.config.STREAMLIT_URL }}
