apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: zeno
    component: api
spec:
  replicas: {{ .Values.api.replicas | default 1 }}
  selector:
    matchLabels:
      app: zeno
      component: api
  template:
    metadata:
      labels:
        app: zeno
        component: api
      annotations:
        force-update: {{ randAlphaNum 5 | quote }}  # random annotation to force update
    spec:
      initContainers:
        - name: s3-data-sync
          image: amazon/aws-cli
          command: ['aws', 's3', 'sync', 's3://zeno-static-data', '/app/data']
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.api.config.AWS_REGION | default "us-east-1" }}"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      containers:
        - name: zeno-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: "IfNotPresent"
          command: ["uv", "run", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: OPENAI_API_KEY
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-zeno-secrets
                  key: ANTHROPIC_API_KEY
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-langfuse-secrets
                  key: LANGFUSE_INIT_PROJECT_SECRET_KEY
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-langfuse-secrets
                  key: LANGFUSE_INIT_PROJECT_PUBLIC_KEY
            - name: LANGFUSE_HOST
              value: {{ .Values.api.config.LANGFUSE_HOST }}
            - name: GEE_SERVICE_ACCOUNT_PATH
              value: /keys/zeno-gee-service-account.json
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: gee-service-account
              mountPath: /keys
              readOnly: true
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: gee-service-account
          secret:
            secretName: {{ .Release.Name }}-zeno-secrets
            items:
              - key: GEE_SERVICE_ACCOUNT_JSON
                path: zeno-gee-service-account.json
