{{- if .Values.pgbouncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgbouncer
  labels:
    app: zeno
    component: pgbouncer
spec:
  replicas: {{ .Values.pgbouncer.replicas | default 1 }}
  selector:
    matchLabels:
      app: zeno
      component: pgbouncer
  template:
    metadata:
      labels:
        app: zeno
        component: pgbouncer
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/pgbouncer-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: pgbouncer
          image: {{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}
          imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: pgbouncer
              containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-pgbouncer-config
          env:
            - name: POSTGRESQL_HOST
              value: {{ .Values.zeno.db_secrets.POSTGRES_HOST | quote }}
            - name: POSTGRESQL_USERNAME
              value: {{ .Values.zeno.db_secrets.POSTGRES_USER | quote }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.zeno.db_secrets.POSTGRES_PASSWORD | quote }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.zeno.db_secrets.POSTGRES_DB | quote }}
          volumeMounts:
            - name: pgbouncer-hba
              mountPath: /etc/pgbouncer
              readOnly: true
          resources:
            {{- toYaml .Values.pgbouncer.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: pgbouncer-hba
          configMap:
            name: {{ .Release.Name }}-pgbouncer-hba
{{- end }}