apiVersion: v1
kind: Secret
metadata:
  name: zeno-langfuse-secrets
data:
{{- range $key, $value := .Values.zeno.langfuse_secrets }}
  {{ $key }}: {{ $value | default "" | b64enc }}
{{- end }}
  
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-zeno-secrets
data:
  # Dynamic secrets from env_secrets (add any new secrets to values.yaml)
{{- range $key, $value := .Values.zeno.env_secrets }}
  {{- if eq $key "GEE_SERVICE_ACCOUNT_JSON" }}
  {{ $key }}: {{ $value | default "" }} # already base64 encoded
  {{- else }}
  {{ $key }}: {{ $value | default "" | b64enc }}
  {{- end }}
{{- end }}
  
  # Computed values
  DATABASE_URL: {{ printf "postgresql+asyncpg://%s:%s@%s/%s" (.Values.zeno.db_secrets.POSTGRES_USER | default "") (.Values.zeno.db_secrets.POSTGRES_PASSWORD | default "") (.Values.zeno.db_secrets.POSTGRES_HOST | default "") (.Values.zeno.db_secrets.POSTGRES_DB | default "") | b64enc }}
  
  # Aliases for compatibility
  LANGFUSE_SECRET_KEY: {{ .Values.zeno.langfuse_secrets.LANGFUSE_INIT_PROJECT_SECRET_KEY | default "" | b64enc }}
  LANGFUSE_PUBLIC_KEY: {{ .Values.zeno.langfuse_secrets.LANGFUSE_INIT_PROJECT_PUBLIC_KEY | default "" | b64enc }}
