apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-langfuse-secrets
data:
  LANGFUSE_INIT_USER_PASSWORD: {{ .Values.zeno.secrets.langfuse.INIT_USER_PASSWORD | default "" | b64enc }}
  LANGFUSE_INIT_PROJECT_SECRET_KEY: {{ .Values.zeno.secrets.langfuse.INIT_PROJECT_SECRET_KEY | default "" | b64enc }}
  LANGFUSE_INIT_PROJECT_PUBLIC_KEY: {{ .Values.zeno.secrets.langfuse.INIT_PROJECT_PUBLIC_KEY | default "" | b64enc }}
  CLICKHOUSE_PASSWORD: {{ .Values.zeno.secrets.langfuse.CLICKHOUSE_PASSWORD | default "" | b64enc }}
  REDIS_PASSWORD: {{ .Values.zeno.secrets.langfuse.REDIS_PASSWORD | default "" | b64enc }}
  
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-zeno-secrets
data:
  OPENAI_API_KEY: {{ .Values.zeno.secrets.api.OPENAI_API_KEY | default "" | b64enc }}
  ANTHROPIC_API_KEY: {{ .Values.zeno.secrets.api.ANTHROPIC_API_KEY | default "" | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.zeno.secrets.api.AWS_ACCESS_KEY_ID | default "" | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.zeno.secrets.api.AWS_SECRET_ACCESS_KEY | default "" | b64enc }}
  MAPBOX_API_TOKEN: {{ .Values.zeno.secrets.api.MAPBOX_API_TOKEN | default "" | b64enc }}
  ELEVENLABS_API_KEY: {{ .Values.zeno.secrets.api.ELEVENLABS_API_KEY | default "" | b64enc }}
  GEE_SERVICE_ACCOUNT_JSON: {{ .Values.zeno.secrets.api.GEE_SERVICE_ACCOUNT_JSON | default "" }} # already base64 encoded
  GFW_DATA_API_KEY: {{ .Values.zeno.secrets.api.GFW_DATA_API_KEY | default "" | b64enc }}
  GFW_DATA_API_USER_ID: {{ .Values.zeno.secrets.api.GFW_DATA_API_USER_ID | default "" | b64enc }}
  DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s/%s" (.Values.zeno.db.POSTGRES_USER | default "") (.Values.zeno.db.POSTGRES_PASSWORD | default "") (.Values.zeno.db.POSTGRES_HOST | default "") (.Values.zeno.db.APP_DB | default "") | b64enc }}
