apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-langfuse-secrets
data:
  LANGFUSE_INIT_USER_PASSWORD: {{ .Values.secrets.langfuse.INIT_USER_PASSWORD | b64enc }}
  LANGFUSE_INIT_PROJECT_SECRET_KEY: {{ .Values.secrets.langfuse.INIT_PROJECT_SECRET_KEY | b64enc }}
  LANGFUSE_INIT_PROJECT_PUBLIC_KEY: {{ .Values.secrets.langfuse.INIT_PROJECT_PUBLIC_KEY | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-zeno-secrets
data:
  OPENAI_API_KEY: {{ .Values.secrets.api.OPENAI_API_KEY | b64enc }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.api.ANTHROPIC_API_KEY | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.api.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.api.AWS_SECRET_ACCESS_KEY | b64enc }}
  MAPBOX_API_TOKEN: {{ .Values.secrets.api.MAPBOX_API_TOKEN | b64enc }}
  ELEVENLABS_API_KEY: {{ .Values.secrets.api.ELEVENLABS_API_KEY | b64enc }}
  GEE_SERVICE_ACCOUNT_JSON: {{ .Values.secrets.api.GEE_SERVICE_ACCOUNT_JSON }} # already base64 encoded
  GFW_DATA_API_KEY: {{ .Values.secrets.api.GFW_DATA_API_KEY | b64enc }}
  GFW_DATA_API_USER_ID: {{ .Values.secrets.api.GFW_DATA_API_USER_ID | b64enc }}
  DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s/%s" .Values.db.POSTGRES_USER .Values.db.POSTGRES_PASSWORD .Values.db.POSTGRES_HOST .Values.db.APP_DB | b64enc }}
