apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-langfuse-secrets
data:
  LANGFUSE_INIT_USER_PASSWORD: {{ .Values.secrets.langfuse.INIT_USER_PASSWORD | b64enc }}
  LANGFUSE_INIT_PROJECT_SECRET_KEY: {{ .Values.secrets.langfuse.INIT_PROJECT_SECRET_KEY | b64enc }}
  LANGFUSE_INIT_PROJECT_PUBLIC_KEY: {{ .Values.secrets.langfuse.INIT_PROJECT_PUBLIC_KEY | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-zeno-secrets
data:
  OPENAI_API_KEY: {{ .Values.secrets.api.OPENAI_API_KEY | b64enc }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.api.ANTHROPIC_API_KEY | b64enc }}
