apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: zeno
    component: api
spec:
  type: ClusterIP
  selector:
    app: zeno
    component: api
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
