apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: zeno
    component: api
spec:
  type: ClusterIP
  selector:
    app: zeno
    component: api
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-streamlit
  labels:
    app: zeno
    component: streamlit
spec:
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: zeno
    component: streamlit
