apiVersion: v2
name: support-chart
description: A Helm chart for support services (monitoring and logging)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 66.3.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
