kube-prometheus-stack:
  grafana:
    ingress:
      hosts:
        - grafana.staging.globalnaturewatch.org
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.staging.globalnaturewatch.org
