name: 'Zeno Evals'

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run in zeno-shell container'
        required: true
        default: "echo 'Hello from zeno-shell!'"
      environment:
        description: 'Environment to run in'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      timeout:
        description: 'Timeout in seconds for command execution'
        required: false
        default: '300'

jobs:
  run-evals:
    name: 'Run Command in Zeno Shell'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    timeout-minutes: 10
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: ${{ inputs.environment }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure Kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name zeno-${{ env.ENVIRONMENT }}-cluster

      - name: Scale up zeno-shell deployment
        id: scale-up
        run: |
          echo "Scaling up zeno-shell deployment to 1 replica..."
          kubectl scale deployment zeno-shell --replicas=1 -n default
          
          echo "Waiting for pod to be ready..."
          kubectl wait --for=condition=ready pod -l app=zeno,component=shell --timeout=300s -n default
          
          POD_NAME=$(kubectl get pods -l app=zeno,component=shell -o jsonpath='{.items[0].metadata.name}' -n default)
          echo "pod_name=$POD_NAME" >> $GITHUB_OUTPUT
          echo "Shell pod is ready: $POD_NAME"

      - name: Execute command in zeno-shell
        id: execute-command
        run: |
          POD_NAME="${{ steps.scale-up.outputs.pod_name }}"
          TIMEOUT="${{ inputs.timeout }}"
          
          echo "Executing command in pod $POD_NAME:"
          echo "Command: ${{ inputs.command }}"
          echo "Timeout: ${TIMEOUT}s"
          echo ""
          echo "=== Command Output ==="
          
          # Execute the command with timeout and capture output
          if timeout ${TIMEOUT}s kubectl exec -i $POD_NAME -n default -- /bin/bash -c '${{ inputs.command }}'; then
            echo ""
            echo "=== Command completed successfully ==="
            echo "exit_code=0" >> $GITHUB_OUTPUT
          else
            EXIT_CODE=$?
            echo ""
            echo "=== Command failed with exit code: $EXIT_CODE ==="
            echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
          fi

      - name: Scale down zeno-shell deployment
        if: always()
        run: |
          echo "Scaling down zeno-shell deployment to 0 replicas..."
          kubectl scale deployment zeno-shell --replicas=0 -n default
          echo "Cleanup completed."

      - name: Command execution summary
        if: always()
        run: |
          EXIT_CODE="${{ steps.execute-command.outputs.exit_code }}"
          
          echo "=== Execution Summary ==="
          echo "Environment: ${{ env.ENVIRONMENT }}"
          echo "Command: ${{ inputs.command }}"
          echo "Exit Code: $EXIT_CODE"
          echo "Pod: ${{ steps.scale-up.outputs.pod_name }}"
          
          if [ "$EXIT_CODE" != "0" ]; then
            echo "❌ Command execution failed"
            exit 1
          else
            echo "✅ Command execution succeeded"
          fi